project:
  type: website

website:
  title: "ishan dahal"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/ishandahal/
      # - icon: twitter
      # href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
